// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package coreelf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type urouterMacEntry struct {
	Address  [6]uint8
	VlanId   uint16
	DomainId uint32
}

type urouterVifEntry struct{ DomainId uint32 }

// loadUrouter returns the embedded CollectionSpec for urouter.
func loadUrouter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UrouterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load urouter: %w", err)
	}

	return spec, err
}

// loadUrouterObjects loads urouter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*urouterObjects
//	*urouterPrograms
//	*urouterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUrouterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUrouter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// urouterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type urouterSpecs struct {
	urouterProgramSpecs
	urouterMapSpecs
}

// urouterSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type urouterProgramSpecs struct {
	XdpPassFn     *ebpf.ProgramSpec `ebpf:"xdp_pass_fn"`
	XdpRedirectFn *ebpf.ProgramSpec `ebpf:"xdp_redirect_fn"`
	XdpRouterFn   *ebpf.ProgramSpec `ebpf:"xdp_router_fn"`
}

// urouterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type urouterMapSpecs struct {
	BridgeTable *ebpf.MapSpec `ebpf:"bridge_table"`
	DomainMap   *ebpf.MapSpec `ebpf:"domain_map"`
	TxPorts     *ebpf.MapSpec `ebpf:"tx_ports"`
	UrouterVif  *ebpf.MapSpec `ebpf:"urouter_vif"`
}

// urouterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUrouterObjects or ebpf.CollectionSpec.LoadAndAssign.
type urouterObjects struct {
	urouterPrograms
	urouterMaps
}

func (o *urouterObjects) Close() error {
	return _UrouterClose(
		&o.urouterPrograms,
		&o.urouterMaps,
	)
}

// urouterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUrouterObjects or ebpf.CollectionSpec.LoadAndAssign.
type urouterMaps struct {
	BridgeTable *ebpf.Map `ebpf:"bridge_table"`
	DomainMap   *ebpf.Map `ebpf:"domain_map"`
	TxPorts     *ebpf.Map `ebpf:"tx_ports"`
	UrouterVif  *ebpf.Map `ebpf:"urouter_vif"`
}

func (m *urouterMaps) Close() error {
	return _UrouterClose(
		m.BridgeTable,
		m.DomainMap,
		m.TxPorts,
		m.UrouterVif,
	)
}

// urouterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUrouterObjects or ebpf.CollectionSpec.LoadAndAssign.
type urouterPrograms struct {
	XdpPassFn     *ebpf.Program `ebpf:"xdp_pass_fn"`
	XdpRedirectFn *ebpf.Program `ebpf:"xdp_redirect_fn"`
	XdpRouterFn   *ebpf.Program `ebpf:"xdp_router_fn"`
}

func (p *urouterPrograms) Close() error {
	return _UrouterClose(
		p.XdpPassFn,
		p.XdpRedirectFn,
		p.XdpRouterFn,
	)
}

func _UrouterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed urouter_bpfel.o
var _UrouterBytes []byte
